name: MicroK8s Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Test on MicroK8s
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microk8s: [stable, edge]
        bundle: [lite, edge]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install test dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo snap install jq
        sudo snap install juju --classic --channel 2.7/stable
        sudo snap install juju-helpers --classic --edge
        sudo snap install juju-wait --classic
        sudo snap install kubectl --classic
        sudo snap install microk8s --classic --channel ${{ matrix.microk8s }}
        sudo snap install yq
        sudo apt update
        sudo apt install -y libssl-dev python3-setuptools
        sudo pip3 install pytest sh kfp requests pyyaml
        sudo usermod -a -G microk8s $USER

    - name: Deploy Kubeflow
      run: |
        set -eux
        git clone git://git.launchpad.net/canonical-osm
        cp -r canonical-osm/charms/interfaces/juju-relation-mysql mysql
        sudo python3 ./scripts/cli.py microk8s setup
        KUBEFLOW_AUTH_PASSWORD=foobar sudo -E python3 ./scripts/cli.py deploy-to uk8s --build --bundle ${{ matrix.bundle }}

    - name: Test Kubeflow
      run: |
        set -eux
        # The pods can sometimes stay in Pending for a little while longer,
        # so run the tests first that don't check pod states.
        ./tests/run.sh -k 'not kubectl' -m ${{ matrix.bundle }}
        ./tests/run.sh -k 'kubectl' -m ${{ matrix.bundle }}

    - name: Print failing logs
      run: |
        set -eux
        sudo microk8s.kubectl get pods -A
        sudo ./tests/dump-pipeline-logs.sh
      if: failure()

